"""
Vehicle Intelligence Module – Database Schema
=============================================
Extends the shared analytics.db with four new tables specific to the
Vehicle Intelligence Module.  Uses the same SQLite + WAL patterns as
the parent application's database.py.

Tables
------
vi_vehicles         Master vehicle registry keyed by plate number.
vi_vehicle_history  Per-detection event log (entry / exit / detection).
vi_watchlist        Plates flagged for special monitoring.
vi_alerts           Security alerts generated by watchlist matches.
"""
from __future__ import annotations

import sqlite3
import time
from typing import Any, Dict, List, Optional

from .config import VI_DB_PATH

_DB_RETRY_ATTEMPTS = 3
_DB_RETRY_BACKOFF = 0.2


# ---------------------------------------------------------------------------
# Low-level helpers (same pattern as database.py)
# ---------------------------------------------------------------------------

def _connect() -> sqlite3.Connection:
    conn = sqlite3.connect(str(VI_DB_PATH), timeout=30, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA busy_timeout=30000")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


def _run_write(action, label: str) -> bool:
    """Execute a write action with retry-on-lock logic."""
    for attempt in range(_DB_RETRY_ATTEMPTS):
        conn: Optional[sqlite3.Connection] = None
        try:
            conn = _connect()
            action(conn)
            conn.commit()
            return True
        except sqlite3.OperationalError as exc:
            locked = "locked" in str(exc).lower() or "busy" in str(exc).lower()
            if conn is not None:
                conn.close()
                conn = None
            if locked and attempt + 1 < _DB_RETRY_ATTEMPTS:
                time.sleep(_DB_RETRY_BACKOFF * (attempt + 1))
                continue
            print(f"[VI DB] Error ({label}): {exc}")
            return False
        except Exception as exc:
            print(f"[VI DB] Error ({label}): {exc}")
            return False
        finally:
            if conn is not None:
                conn.close()
    return False


def _query(sql: str, params: tuple = ()) -> List[Dict[str, Any]]:
    """Execute a SELECT and return rows as dicts."""
    conn: Optional[sqlite3.Connection] = None
    try:
        conn = _connect()
        rows = conn.execute(sql, params).fetchall()
        return [dict(row) for row in rows]
    except Exception as exc:
        print(f"[VI DB] Query error: {exc}")
        return []
    finally:
        if conn is not None:
            conn.close()


def _query_one(sql: str, params: tuple = ()) -> Optional[Dict[str, Any]]:
    rows = _query(sql, params)
    return rows[0] if rows else None


# ---------------------------------------------------------------------------
# Schema initialisation
# ---------------------------------------------------------------------------

def vi_init_db() -> None:
    """Create all Vehicle Intelligence tables and indexes (idempotent)."""
    conn = _connect()
    try:
        # ------------------------------------------------------------------
        # vi_vehicles – Master registry, one row per unique plate
        # ------------------------------------------------------------------
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS vi_vehicles (
                id               INTEGER PRIMARY KEY AUTOINCREMENT,
                plate_text       TEXT    NOT NULL UNIQUE,
                vehicle_type     TEXT,
                registered_owner TEXT,
                notes            TEXT,
                total_detections INTEGER NOT NULL DEFAULT 1,
                first_seen       DATETIME DEFAULT CURRENT_TIMESTAMP,
                last_seen        DATETIME DEFAULT CURRENT_TIMESTAMP
            )
            """
        )

        # ------------------------------------------------------------------
        # vi_vehicle_history – One row per detection event
        # ------------------------------------------------------------------
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS vi_vehicle_history (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                plate_text      TEXT    NOT NULL,
                camera_id       TEXT    NOT NULL,
                camera_location TEXT,
                timestamp       DATETIME DEFAULT CURRENT_TIMESTAMP,
                event_type      TEXT    NOT NULL DEFAULT 'detection',
                vehicle_type    TEXT,
                confidence      REAL,
                ocr_source      TEXT    DEFAULT 'unknown'
            )
            """
        )

        # ------------------------------------------------------------------
        # vi_watchlist – Plates flagged for monitoring
        # ------------------------------------------------------------------
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS vi_watchlist (
                id         INTEGER PRIMARY KEY AUTOINCREMENT,
                plate_text TEXT    NOT NULL UNIQUE,
                reason     TEXT,
                priority   INTEGER NOT NULL DEFAULT 2,
                added_at   DATETIME DEFAULT CURRENT_TIMESTAMP,
                added_by   TEXT    DEFAULT 'system',
                is_active  INTEGER NOT NULL DEFAULT 1
            )
            """
        )

        # ------------------------------------------------------------------
        # vi_alerts – Security alerts produced by watchlist matches
        # ------------------------------------------------------------------
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS vi_alerts (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                plate_text      TEXT    NOT NULL,
                camera_id       TEXT    NOT NULL,
                camera_location TEXT,
                timestamp       DATETIME DEFAULT CURRENT_TIMESTAMP,
                alert_type      TEXT    NOT NULL DEFAULT 'watchlist_match',
                priority        INTEGER NOT NULL DEFAULT 2,
                message         TEXT,
                acknowledged    INTEGER NOT NULL DEFAULT 0
            )
            """
        )

        # ------------------------------------------------------------------
        # Indexes
        # ------------------------------------------------------------------
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_vi_history_plate "
            "ON vi_vehicle_history(plate_text)"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_vi_history_cam_ts "
            "ON vi_vehicle_history(camera_id, timestamp DESC)"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_vi_alerts_ts "
            "ON vi_alerts(timestamp DESC)"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_vi_alerts_plate "
            "ON vi_alerts(plate_text)"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_vi_watchlist_active "
            "ON vi_watchlist(plate_text, is_active)"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_vi_vehicles_plate "
            "ON vi_vehicles(plate_text)"
        )

        conn.commit()
        print("[VI] Database schema ready.")
    finally:
        conn.close()
